<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<IncludeHttpRuleProtos>true</IncludeHttpRuleProtos>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.33.5" />
    <PackageReference Include="Grpc.Tools" Version="2.78.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="10.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\Static\gtfs-realtime.proto" GrpcServices="None" />
	<Protobuf Include="Protos\auth.proto" GrpcServices="Both" />
	<Protobuf Include="Protos\driver-ops.proto" GrpcServices="Both" />
  </ItemGroup>

</Project>
