// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using PassengerManager.Shared.Models;

namespace PassengerManager.Server.Models;

public partial class PassengerManagerContext : DbContext
{
    public PassengerManagerContext(DbContextOptions<PassengerManagerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Agency> Agencies { get; set; }

    public virtual DbSet<LoginAudit> LoginAudits { get; set; }

    public virtual DbSet<PasswordHistory> PasswordHistories { get; set; }

    public virtual DbSet<Shared.Models.Route> Routes { get; set; }

    public virtual DbSet<ServiceAlert> ServiceAlerts { get; set; }

    public virtual DbSet<ShapeHeader> ShapeHeaders { get; set; }

    public virtual DbSet<ShapePoint> ShapePoints { get; set; }

    public virtual DbSet<Shift> Shifts { get; set; }

    public virtual DbSet<Stop> Stops { get; set; }

    public virtual DbSet<Telemetry> Telemetries { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<Trip> Trips { get; set; }

    public virtual DbSet<TripUpdate> TripUpdates { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Agency>(entity =>
        {
            entity.HasKey(e => e.AgencyId).HasName("agencies_pkey");

            entity.ToTable("agencies");

            entity.Property(e => e.AgencyId)
                .HasMaxLength(128)
                .HasColumnName("agency_id");
            entity.Property(e => e.Lang)
                .HasMaxLength(10)
                .HasDefaultValueSql("'uk'::character varying")
                .HasColumnName("lang");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name");
            entity.Property(e => e.Phone)
                .HasMaxLength(50)
                .HasColumnName("phone");
            entity.Property(e => e.Timezone)
                .HasMaxLength(50)
                .HasDefaultValueSql("'Europe/Kyiv'::character varying")
                .HasColumnName("timezone");
            entity.Property(e => e.Url).HasColumnName("url");
        });

        modelBuilder.Entity<LoginAudit>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("login_audit_pkey");

            entity.ToTable("login_audit");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AttemptTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("attempt_time");
            entity.Property(e => e.IpAddress)
                .HasMaxLength(45)
                .HasColumnName("ip_address");
            entity.Property(e => e.IsSuccess).HasColumnName("is_success");
            entity.Property(e => e.UserAgent).HasColumnName("user_agent");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.UsernameAttempted)
                .HasMaxLength(50)
                .HasColumnName("username_attempted");

            entity.HasOne(d => d.User).WithMany(p => p.LoginAudits)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("login_audit_user_id_fkey");
        });

        modelBuilder.Entity<PasswordHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("password_history_pkey");

            entity.ToTable("password_history");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasColumnName("password_hash");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.PasswordHistories)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("password_history_user_id_fkey");
        });

        modelBuilder.Entity<Shared.Models.Route>(entity =>
        {
            entity.HasKey(e => e.RouteId).HasName("routes_pkey");

            entity.ToTable("routes");

            entity.Property(e => e.RouteId)
                .HasMaxLength(128)
                .HasColumnName("route_id");
            entity.Property(e => e.AgencyId)
                .HasMaxLength(128)
                .HasColumnName("agency_id");
            entity.Property(e => e.Color)
                .HasMaxLength(10)
                .HasDefaultValueSql("'#000000'::character varying")
                .HasColumnName("color");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.LongName).HasColumnName("long_name");
            entity.Property(e => e.ShortName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("short_name");
            entity.Property(e => e.SortOrder).HasColumnName("sort_order");
            entity.Property(e => e.TextColor)
                .HasMaxLength(10)
                .HasDefaultValueSql("'#FFFFFF'::character varying")
                .HasColumnName("text_color");
            entity.Property(e => e.Type).HasColumnName("type");
            entity.Property(e => e.Url).HasColumnName("url");

            entity.HasOne(d => d.Agency).WithMany(p => p.Routes)
                .HasForeignKey(d => d.AgencyId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("routes_agency_id_fkey");
        });

        modelBuilder.Entity<ServiceAlert>(entity =>
        {
            entity.HasKey(e => e.AlertId).HasName("service_alerts_pkey");

            entity.ToTable("service_alerts");

            entity.HasIndex(e => e.RouteId, "idx_alerts_active_route").HasFilter("(is_active = true)");

            entity.Property(e => e.AlertId)
                .HasMaxLength(128)
                .HasColumnName("alert_id");
            entity.Property(e => e.AgencyId)
                .HasMaxLength(128)
                .HasColumnName("agency_id");
            entity.Property(e => e.Cause).HasColumnName("cause");
            entity.Property(e => e.DescriptionText).HasColumnName("description_text");
            entity.Property(e => e.Effect).HasColumnName("effect");
            entity.Property(e => e.EndTime).HasColumnName("end_time");
            entity.Property(e => e.HeaderText)
                .IsRequired()
                .HasColumnName("header_text");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.RouteId)
                .HasMaxLength(128)
                .HasColumnName("route_id");
            entity.Property(e => e.StartTime).HasColumnName("start_time");
            entity.Property(e => e.StopId)
                .HasMaxLength(128)
                .HasColumnName("stop_id");

            entity.HasOne(d => d.Agency).WithMany(p => p.ServiceAlerts)
                .HasForeignKey(d => d.AgencyId)
                .HasConstraintName("service_alerts_agency_id_fkey");

            entity.HasOne(d => d.Route).WithMany(p => p.ServiceAlerts)
                .HasForeignKey(d => d.RouteId)
                .HasConstraintName("service_alerts_route_id_fkey");

            entity.HasOne(d => d.Stop).WithMany(p => p.ServiceAlerts)
                .HasForeignKey(d => d.StopId)
                .HasConstraintName("service_alerts_stop_id_fkey");
        });

        modelBuilder.Entity<ShapeHeader>(entity =>
        {
            entity.HasKey(e => e.ShapeId).HasName("shape_headers_pkey");

            entity.ToTable("shape_headers");

            entity.Property(e => e.ShapeId)
                .HasMaxLength(128)
                .HasColumnName("shape_id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.TotalDistanceMeters).HasColumnName("total_distance_meters");
        });

        modelBuilder.Entity<ShapePoint>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("shape_points_pkey");

            entity.ToTable("shape_points");

            entity.HasIndex(e => new { e.ShapeId, e.Sequence }, "idx_shape_points_sequence");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.DistTraveled).HasColumnName("dist_traveled");
            entity.Property(e => e.Latitude).HasColumnName("latitude");
            entity.Property(e => e.Longitude).HasColumnName("longitude");
            entity.Property(e => e.Sequence).HasColumnName("sequence");
            entity.Property(e => e.ShapeId)
                .HasMaxLength(128)
                .HasColumnName("shape_id");

            entity.HasOne(d => d.Shape).WithMany(p => p.ShapePoints)
                .HasForeignKey(d => d.ShapeId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("shape_points_shape_id_fkey");
        });

        modelBuilder.Entity<Shift>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("shifts_pkey");

            entity.ToTable("shifts");

            entity.HasIndex(e => e.VehicleId, "idx_shifts_active").HasFilter("(end_time IS NULL)");

            entity.HasIndex(e => e.UserId, "idx_shifts_user");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.EndTime).HasColumnName("end_time");
            entity.Property(e => e.IsApproved)
                .HasDefaultValue(true)
                .HasColumnName("is_approved");
            entity.Property(e => e.StartTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("start_time");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.VehicleId)
                .HasMaxLength(128)
                .HasColumnName("vehicle_id");

            entity.HasOne(d => d.User).WithMany(p => p.Shifts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("shifts_user_id_fkey");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Shifts)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("shifts_vehicle_id_fkey");
        });

        modelBuilder.Entity<Stop>(entity =>
        {
            entity.HasKey(e => e.StopId).HasName("stops_pkey");

            entity.ToTable("stops");

            entity.HasIndex(e => new { e.Latitude, e.Longitude }, "idx_stops_lat_lon");

            entity.Property(e => e.StopId)
                .HasMaxLength(128)
                .HasColumnName("stop_id");
            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .HasColumnName("code");
            entity.Property(e => e.Latitude).HasColumnName("latitude");
            entity.Property(e => e.LocationType)
                .HasDefaultValue(0)
                .HasColumnName("location_type");
            entity.Property(e => e.Longitude).HasColumnName("longitude");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name");
            entity.Property(e => e.PlatformCode).HasColumnName("platform_code");
            entity.Property(e => e.WheelchairBoarding)
                .HasDefaultValue(0)
                .HasColumnName("wheelchair_boarding");
        });

        modelBuilder.Entity<Telemetry>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("telemetry_pkey");

            entity.ToTable("telemetry");

            entity.HasIndex(e => new { e.RouteId, e.Timestamp }, "idx_telemetry_route_time").IsDescending(false, true);

            entity.HasIndex(e => e.Timestamp, "idx_telemetry_timestamp");

            entity.HasIndex(e => new { e.VehicleId, e.Timestamp }, "idx_telemetry_vehicle_time").IsDescending(false, true);

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Bearing).HasColumnName("bearing");
            entity.Property(e => e.CongestionLevel).HasColumnName("congestion_level");
            entity.Property(e => e.CurrentStatus).HasColumnName("current_status");
            entity.Property(e => e.CurrentStopSequence).HasColumnName("current_stop_sequence");
            entity.Property(e => e.Latitude).HasColumnName("latitude");
            entity.Property(e => e.Longitude).HasColumnName("longitude");
            entity.Property(e => e.OccupancyStatus).HasColumnName("occupancy_status");
            entity.Property(e => e.Odometer).HasColumnName("odometer");
            entity.Property(e => e.RouteId)
                .HasMaxLength(128)
                .HasColumnName("route_id");
            entity.Property(e => e.Speed).HasColumnName("speed");
            entity.Property(e => e.StopId)
                .HasMaxLength(128)
                .HasColumnName("stop_id");
            entity.Property(e => e.Timestamp)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("timestamp");
            entity.Property(e => e.TripId)
                .HasMaxLength(128)
                .HasColumnName("trip_id");
            entity.Property(e => e.VehicleId)
                .HasMaxLength(128)
                .HasColumnName("vehicle_id");
            entity.Property(e => e.DriverId)
                .HasColumnName("driver_id");

            entity.HasOne(d => d.Route).WithMany(p => p.Telemetries)
                .HasForeignKey(d => d.RouteId)
                .HasConstraintName("telemetry_route_id_fkey");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Telemetries)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("telemetry_vehicle_id_fkey");

            entity.HasOne(d => d.Driver).WithMany()
                .HasForeignKey(d => d.DriverId)
                .HasConstraintName("telemetry_driver_id_fkey");
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.TransactionUuid).HasName("transactions_pkey");

            entity.ToTable("transactions");

            entity.HasIndex(e => e.RouteId, "idx_transactions_route");

            entity.HasIndex(e => e.Timestamp, "idx_transactions_time");

            entity.Property(e => e.TransactionUuid)
                .ValueGeneratedNever()
                .HasColumnName("transaction_uuid");
            entity.Property(e => e.Amount)
                .HasPrecision(10, 2)
                .HasColumnName("amount");
            entity.Property(e => e.Currency)
                .HasMaxLength(3)
                .HasDefaultValueSql("'UAH'::character varying")
                .HasColumnName("currency");
            entity.Property(e => e.Latitude).HasColumnName("latitude");
            entity.Property(e => e.Longitude).HasColumnName("longitude");
            entity.Property(e => e.RouteId)
                .HasMaxLength(128)
                .HasColumnName("route_id");
            entity.Property(e => e.SyncedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("synced_at");
            entity.Property(e => e.TicketType)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("ticket_type");
            entity.Property(e => e.Timestamp).HasColumnName("timestamp");
            entity.Property(e => e.VehicleId)
                .HasMaxLength(128)
                .HasColumnName("vehicle_id");

            entity.HasOne(d => d.Route).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.RouteId)
                .HasConstraintName("transactions_route_id_fkey");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.VehicleId)
                .HasConstraintName("transactions_vehicle_id_fkey");
        });

        modelBuilder.Entity<Trip>(entity =>
        {
            entity.HasKey(e => e.TripId).HasName("trips_pkey");

            entity.ToTable("trips");

            entity.HasIndex(e => e.RouteId, "idx_trips_route");

            entity.HasIndex(e => e.ShapeId, "idx_trips_shapes");

            entity.Property(e => e.TripId)
                .HasMaxLength(128)
                .HasColumnName("trip_id");
            entity.Property(e => e.DirectionId).HasColumnName("direction_id");
            entity.Property(e => e.Headsign).HasColumnName("headsign");
            entity.Property(e => e.RouteId)
                .HasMaxLength(128)
                .HasColumnName("route_id");
            entity.Property(e => e.ServiceId)
                .HasMaxLength(128)
                .HasColumnName("service_id");
            entity.Property(e => e.ShapeId)
                .HasMaxLength(128)
                .HasColumnName("shape_id");

            entity.HasOne(d => d.Route).WithMany(p => p.Trips)
                .HasForeignKey(d => d.RouteId)
                .HasConstraintName("trips_route_id_fkey");

            entity.HasOne(d => d.Shape).WithMany(p => p.Trips)
                .HasForeignKey(d => d.ShapeId)
                .HasConstraintName("trips_shape_id_fkey");
        });

        modelBuilder.Entity<TripUpdate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("trip_updates_pkey");

            entity.ToTable("trip_updates");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.DelaySeconds).HasColumnName("delay_seconds");
            entity.Property(e => e.Timestamp).HasColumnName("timestamp");
            entity.Property(e => e.TripId)
                .HasMaxLength(128)
                .HasColumnName("trip_id");
            entity.Property(e => e.VehicleId)
                .HasMaxLength(128)
                .HasColumnName("vehicle_id");

            entity.HasOne(d => d.Trip).WithMany(p => p.TripUpdates)
                .HasForeignKey(d => d.TripId)
                .HasConstraintName("trip_updates_trip_id_fkey");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.TripUpdates)
                .HasForeignKey(d => d.VehicleId)
                .HasConstraintName("trip_updates_vehicle_id_fkey");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("users_pkey");

            entity.ToTable("users");

            entity.HasIndex(e => e.Username, "users_username_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AgencyId)
                .HasMaxLength(128)
                .HasColumnName("agency_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.FailedLoginAttempts)
                .HasDefaultValue(0)
                .HasColumnName("failed_login_attempts");
            entity.Property(e => e.FullName).HasColumnName("full_name");
            entity.Property(e => e.IsLockedOut)
                .HasDefaultValue(false)
                .HasColumnName("is_locked_out");
            entity.Property(e => e.LastLogin).HasColumnName("last_login");
            entity.Property(e => e.LockoutEnd).HasColumnName("lockout_end");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasColumnName("password_hash");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("username");

            entity.HasOne(d => d.Agency).WithMany(p => p.Users)
                .HasForeignKey(d => d.AgencyId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("users_agency_id_fkey");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("users_role_id_fkey");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("user_roles_pkey");

            entity.ToTable("user_roles");

            entity.HasIndex(e => e.RoleName, "user_roles_role_name_key").IsUnique();

            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.AccessLevel)
                .HasDefaultValue(10)
                .HasColumnName("access_level");
            entity.Property(e => e.DefaultWindow)
                .HasMaxLength(100)
                .HasColumnName("default_window");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("role_name");
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.VehicleId).HasName("vehicles_pkey");

            entity.ToTable("vehicles");

            entity.HasIndex(e => e.AgencyId, "idx_vehicles_active").HasFilter("(is_active = true)");

            entity.HasIndex(e => e.LicensePlate, "vehicles_license_plate_key").IsUnique();

            entity.Property(e => e.VehicleId)
                .HasMaxLength(128)
                .HasColumnName("vehicle_id");
            entity.Property(e => e.AgencyId)
                .HasMaxLength(128)
                .HasColumnName("agency_id");
            entity.Property(e => e.HardwareHash)
                .HasDefaultValue("UNSET")
                .HasColumnName("hardware_hash");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.LastMaintenance).HasColumnName("last_maintenance");
            entity.Property(e => e.LicensePlate)
                .HasMaxLength(20)
                .HasColumnName("license_plate");
            entity.Property(e => e.ManufactureYear).HasColumnName("manufacture_year");
            entity.Property(e => e.Model)
                .HasMaxLength(100)
                .HasColumnName("model");

            entity.HasOne(d => d.Agency).WithMany(p => p.Vehicles)
                .HasForeignKey(d => d.AgencyId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("vehicles_agency_id_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}