// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PassengerManager.Shared.Models;

public partial class Agency
{
    public string AgencyId { get; set; }

    public string Name { get; set; }

    public string Url { get; set; }

    public string Timezone { get; set; }

    public string Phone { get; set; }

    public string Lang { get; set; }

    public virtual ICollection<Route> Routes { get; set; } = new List<Route>();

    public virtual ICollection<ServiceAlert> ServiceAlerts { get; set; } = new List<ServiceAlert>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}