// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PassengerManager.Shared.Models;

public partial class LoginAudit
{
    public long Id { get; set; }

    public int? UserId { get; set; }

    public string UsernameAttempted { get; set; }

    public DateTime? AttemptTime { get; set; }

    public bool IsSuccess { get; set; }

    public string IpAddress { get; set; }

    public string UserAgent { get; set; }

    public virtual User User { get; set; }
}