// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PassengerManager.Shared.Models;

public partial class Route
{
    public string RouteId { get; set; }

    public string AgencyId { get; set; }

    public string ShortName { get; set; }

    public string LongName { get; set; }

    public string Description { get; set; }

    public string Url { get; set; }

    public int? Type { get; set; }

    public int? SortOrder { get; set; }

    public string Color { get; set; }

    public string TextColor { get; set; }

    public virtual Agency Agency { get; set; }

    public virtual ICollection<ServiceAlert> ServiceAlerts { get; set; } = new List<ServiceAlert>();

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();

    public virtual ICollection<Telemetry> Telemetries { get; set; } = new List<Telemetry>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();
}