// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PassengerManager.Shared.Models;

public partial class ServiceAlert
{
    public string AlertId { get; set; }

    public string AgencyId { get; set; }

    public string RouteId { get; set; }

    public string StopId { get; set; }

    public string HeaderText { get; set; }

    public string DescriptionText { get; set; }

    public int? Cause { get; set; }

    public int? Effect { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public bool? IsActive { get; set; }

    public virtual Agency Agency { get; set; }

    public virtual Route Route { get; set; }

    public virtual Stop Stop { get; set; }
}