// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PassengerManager.Shared.Models;

public partial class ShapePoint
{
    public long Id { get; set; }

    public string ShapeId { get; set; }

    public double Latitude { get; set; }

    public double Longitude { get; set; }

    public int Sequence { get; set; }

    public double? DistTraveled { get; set; }

    public virtual ShapeHeader Shape { get; set; }
}