// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PassengerManager.Shared.Models;

public partial class ShapeHeader
{
    public string ShapeId { get; set; }

    public string Description { get; set; }

    public double? TotalDistanceMeters { get; set; }

    public virtual ICollection<ShapePoint> ShapePoints { get; set; } = new List<ShapePoint>();

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();
}