// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PassengerManager.Shared.Models;

public partial class Shift
{
    public long Id { get; set; }

    public int? UserId { get; set; }

    public string VehicleId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public bool? IsApproved { get; set; }

    public virtual User User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}