// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PassengerManager.Shared.Models;

public partial class Stop
{
    public string StopId { get; set; }

    public string Name { get; set; }

    public double Latitude { get; set; }

    public double Longitude { get; set; }

    public int? WheelchairBoarding { get; set; }

    public int? LocationType { get; set; }

    public string PlatformCode { get; set; }

    public string Code { get; set; }

    public virtual ICollection<ServiceAlert> ServiceAlerts { get; set; } = new List<ServiceAlert>();
}