// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PassengerManager.Shared.Models;

public partial class Telemetry
{
    public long Id { get; set; }

    public string VehicleId { get; set; }

    public string RouteId { get; set; }

    public string TripId { get; set; }

    public int? DriverId { get; set; }

    public double Latitude { get; set; }

    public double Longitude { get; set; }

    public double? Bearing { get; set; }

    public double? Speed { get; set; }

    public double? Odometer { get; set; }

    public int? CurrentStatus { get; set; }

    public string StopId { get; set; }

    public int? CurrentStopSequence { get; set; }

    public int? CongestionLevel { get; set; }

    public int? OccupancyStatus { get; set; }

    public DateTime? Timestamp { get; set; }

    public virtual Route Route { get; set; }

    public virtual Vehicle Vehicle { get; set; }

    public virtual User Driver { get; set; }
}