// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PassengerManager.Shared.Models;

public partial class Transaction
{
    public Guid TransactionUuid { get; set; }

    public string VehicleId { get; set; }

    public string RouteId { get; set; }

    public string TicketType { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public DateTime Timestamp { get; set; }

    public DateTime? SyncedAt { get; set; }

    public virtual Route Route { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}