// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PassengerManager.Shared.Models;

public partial class Trip
{
    public string TripId { get; set; }

    public string RouteId { get; set; }

    public string ServiceId { get; set; }

    public string Headsign { get; set; }

    public int? DirectionId { get; set; }

    public string ShapeId { get; set; }

    public virtual Route Route { get; set; }

    public virtual ShapeHeader Shape { get; set; }

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();

    public virtual ICollection<TripUpdate> TripUpdates { get; set; } = new List<TripUpdate>();
}