// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PassengerManager.Shared.Models;

public partial class TripUpdate
{
    public long Id { get; set; }

    public string TripId { get; set; }

    public string VehicleId { get; set; }

    public DateTime? Timestamp { get; set; }

    public int? DelaySeconds { get; set; }

    public virtual Trip Trip { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}