// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PassengerManager.Shared.Models;

public partial class User
{
    public int Id { get; set; }

    public string AgencyId { get; set; }

    public int RoleId { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string FullName { get; set; }

    public bool? IsLockedOut { get; set; }

    public int? FailedLoginAttempts { get; set; }

    public DateTime? LockoutEnd { get; set; }

    public DateTime? LastLogin { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Agency Agency { get; set; }

    public virtual ICollection<LoginAudit> LoginAudits { get; set; } = new List<LoginAudit>();

    public virtual ICollection<PasswordHistory> PasswordHistories { get; set; } = new List<PasswordHistory>();

    public virtual UserRole Role { get; set; }

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();
}