// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PassengerManager.Shared.Models;

public partial class Vehicle
{
    public string VehicleId { get; set; }

    public string AgencyId { get; set; }

    public string LicensePlate { get; set; }

    public string Model { get; set; }

    public string HardwareHash { get; set; } = "UNSET";

    public int? ManufactureYear { get; set; }

    public bool? IsActive { get; set; }

    public DateOnly? LastMaintenance { get; set; }

    public virtual Agency Agency { get; set; }

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();

    public virtual ICollection<Telemetry> Telemetries { get; set; } = new List<Telemetry>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual ICollection<TripUpdate> TripUpdates { get; set; } = new List<TripUpdate>();
}