// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PassengerManager.Server.Models;

#nullable disable

namespace PassengerManager.Server.Migrations
{
    [DbContext(typeof(PassengerManagerContext))]
    [Migration("20260409122636_AddVehicleHardwareHash")]
    partial class AddVehicleHardwareHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PassengerManager.Shared.Models.Agency", b =>
                {
                    b.Property<string>("AgencyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agency_id");

                    b.Property<string>("Lang")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("lang")
                        .HasDefaultValueSql("'uk'::character varying");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Timezone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("timezone")
                        .HasDefaultValueSql("'Europe/Kyiv'::character varying");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("AgencyId")
                        .HasName("agencies_pkey");

                    b.ToTable("agencies", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.LoginAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AttemptTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempt_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("UsernameAttempted")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username_attempted");

                    b.HasKey("Id")
                        .HasName("login_audit_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("login_audit", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.PasswordHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("password_history_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("password_history", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Route", b =>
                {
                    b.Property<string>("RouteId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("route_id");

                    b.Property<string>("AgencyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agency_id");

                    b.Property<string>("Color")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("color")
                        .HasDefaultValueSql("'#000000'::character varying");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LongName")
                        .HasColumnType("text")
                        .HasColumnName("long_name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("short_name");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TextColor")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("text_color")
                        .HasDefaultValueSql("'#FFFFFF'::character varying");

                    b.Property<int?>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("RouteId")
                        .HasName("routes_pkey");

                    b.HasIndex("AgencyId");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.ServiceAlert", b =>
                {
                    b.Property<string>("AlertId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("alert_id");

                    b.Property<string>("AgencyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agency_id");

                    b.Property<int?>("Cause")
                        .HasColumnType("integer")
                        .HasColumnName("cause");

                    b.Property<string>("DescriptionText")
                        .HasColumnType("text")
                        .HasColumnName("description_text");

                    b.Property<int?>("Effect")
                        .HasColumnType("integer")
                        .HasColumnName("effect");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("HeaderText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("header_text");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("RouteId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("route_id");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("StopId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stop_id");

                    b.HasKey("AlertId")
                        .HasName("service_alerts_pkey");

                    b.HasIndex("AgencyId");

                    b.HasIndex("StopId");

                    b.HasIndex(new[] { "RouteId" }, "idx_alerts_active_route")
                        .HasFilter("(is_active = true)");

                    b.ToTable("service_alerts", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.ShapeHeader", b =>
                {
                    b.Property<string>("ShapeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("shape_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double?>("TotalDistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("total_distance_meters");

                    b.HasKey("ShapeId")
                        .HasName("shape_headers_pkey");

                    b.ToTable("shape_headers", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.ShapePoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("DistTraveled")
                        .HasColumnType("double precision")
                        .HasColumnName("dist_traveled");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("ShapeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("shape_id");

                    b.HasKey("Id")
                        .HasName("shape_points_pkey");

                    b.HasIndex(new[] { "ShapeId", "Sequence" }, "idx_shape_points_sequence");

                    b.ToTable("shape_points", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Shift", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_approved");

                    b.Property<DateTime?>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("VehicleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("shifts_pkey");

                    b.HasIndex(new[] { "VehicleId" }, "idx_shifts_active")
                        .HasFilter("(end_time IS NULL)");

                    b.HasIndex(new[] { "UserId" }, "idx_shifts_user");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Stop", b =>
                {
                    b.Property<string>("StopId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stop_id");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<int?>("LocationType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("location_type");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PlatformCode")
                        .HasColumnType("text")
                        .HasColumnName("platform_code");

                    b.Property<int?>("WheelchairBoarding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("wheelchair_boarding");

                    b.HasKey("StopId")
                        .HasName("stops_pkey");

                    b.HasIndex(new[] { "Latitude", "Longitude" }, "idx_stops_lat_lon");

                    b.ToTable("stops", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Telemetry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Bearing")
                        .HasColumnType("double precision")
                        .HasColumnName("bearing");

                    b.Property<int?>("CongestionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("congestion_level");

                    b.Property<int?>("CurrentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("current_status");

                    b.Property<int?>("CurrentStopSequence")
                        .HasColumnType("integer")
                        .HasColumnName("current_stop_sequence");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int?>("OccupancyStatus")
                        .HasColumnType("integer")
                        .HasColumnName("occupancy_status");

                    b.Property<double?>("Odometer")
                        .HasColumnType("double precision")
                        .HasColumnName("odometer");

                    b.Property<string>("RouteId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("route_id");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<string>("StopId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stop_id");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TripId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trip_id");

                    b.Property<string>("VehicleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("telemetry_pkey");

                    b.HasIndex("DriverId");

                    b.HasIndex(new[] { "RouteId", "Timestamp" }, "idx_telemetry_route_time")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "Timestamp" }, "idx_telemetry_timestamp");

                    b.HasIndex(new[] { "VehicleId", "Timestamp" }, "idx_telemetry_vehicle_time")
                        .IsDescending(false, true);

                    b.ToTable("telemetry", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'UAH'::character varying");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("RouteId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("route_id");

                    b.Property<DateTime?>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ticket_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("VehicleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("TransactionUuid")
                        .HasName("transactions_pkey");

                    b.HasIndex("VehicleId");

                    b.HasIndex(new[] { "RouteId" }, "idx_transactions_route");

                    b.HasIndex(new[] { "Timestamp" }, "idx_transactions_time");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Trip", b =>
                {
                    b.Property<string>("TripId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trip_id");

                    b.Property<int?>("DirectionId")
                        .HasColumnType("integer")
                        .HasColumnName("direction_id");

                    b.Property<string>("Headsign")
                        .HasColumnType("text")
                        .HasColumnName("headsign");

                    b.Property<string>("RouteId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("route_id");

                    b.Property<string>("ServiceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("service_id");

                    b.Property<string>("ShapeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("shape_id");

                    b.HasKey("TripId")
                        .HasName("trips_pkey");

                    b.HasIndex(new[] { "RouteId" }, "idx_trips_route");

                    b.HasIndex(new[] { "ShapeId" }, "idx_trips_shapes");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.TripUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("DelaySeconds")
                        .HasColumnType("integer")
                        .HasColumnName("delay_seconds");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("TripId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trip_id");

                    b.Property<string>("VehicleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("trip_updates_pkey");

                    b.HasIndex("TripId");

                    b.HasIndex("VehicleId");

                    b.ToTable("trip_updates", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgencyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agency_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool?>("IsLockedOut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked_out");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("AgencyId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<int>("AccessLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("access_level");

                    b.Property<string>("DefaultWindow")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("default_window");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("user_roles_pkey");

                    b.HasIndex(new[] { "RoleName" }, "user_roles_role_name_key")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            AccessLevel = 100,
                            DefaultWindow = "AdminDashboard",
                            Description = "Full database control. Developed for persons responsible for transportation management, such as within the city council.",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            RoleId = 2,
                            AccessLevel = 50,
                            DefaultWindow = "DispatcherDashboard",
                            Description = "Incident management control. Developed for persons responsible for transportation monitoring, such as depot dispatchers.",
                            RoleName = "Dispatcher"
                        },
                        new
                        {
                            RoleId = 3,
                            AccessLevel = 10,
                            DefaultWindow = "DriverView",
                            Description = "Current route control. Developed for use in tablets inside driver compartments of transportational vehicles.",
                            RoleName = "Driver"
                        });
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Vehicle", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("AgencyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agency_id");

                    b.Property<string>("HardwareHash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("UNSET")
                        .HasColumnName("hardware_hash");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateOnly?>("LastMaintenance")
                        .HasColumnType("date")
                        .HasColumnName("last_maintenance");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<int?>("ManufactureYear")
                        .HasColumnType("integer")
                        .HasColumnName("manufacture_year");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.HasKey("VehicleId")
                        .HasName("vehicles_pkey");

                    b.HasIndex(new[] { "AgencyId" }, "idx_vehicles_active")
                        .HasFilter("(is_active = true)");

                    b.HasIndex(new[] { "LicensePlate" }, "vehicles_license_plate_key")
                        .IsUnique();

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.LoginAudit", b =>
                {
                    b.HasOne("PassengerManager.Shared.Models.User", "User")
                        .WithMany("LoginAudits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("login_audit_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.PasswordHistory", b =>
                {
                    b.HasOne("PassengerManager.Shared.Models.User", "User")
                        .WithMany("PasswordHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("password_history_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Route", b =>
                {
                    b.HasOne("PassengerManager.Shared.Models.Agency", "Agency")
                        .WithMany("Routes")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("routes_agency_id_fkey");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.ServiceAlert", b =>
                {
                    b.HasOne("PassengerManager.Shared.Models.Agency", "Agency")
                        .WithMany("ServiceAlerts")
                        .HasForeignKey("AgencyId")
                        .HasConstraintName("service_alerts_agency_id_fkey");

                    b.HasOne("PassengerManager.Shared.Models.Route", "Route")
                        .WithMany("ServiceAlerts")
                        .HasForeignKey("RouteId")
                        .HasConstraintName("service_alerts_route_id_fkey");

                    b.HasOne("PassengerManager.Shared.Models.Stop", "Stop")
                        .WithMany("ServiceAlerts")
                        .HasForeignKey("StopId")
                        .HasConstraintName("service_alerts_stop_id_fkey");

                    b.Navigation("Agency");

                    b.Navigation("Route");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.ShapePoint", b =>
                {
                    b.HasOne("PassengerManager.Shared.Models.ShapeHeader", "Shape")
                        .WithMany("ShapePoints")
                        .HasForeignKey("ShapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("shape_points_shape_id_fkey");

                    b.Navigation("Shape");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Shift", b =>
                {
                    b.HasOne("PassengerManager.Shared.Models.User", "User")
                        .WithMany("Shifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("shifts_user_id_fkey");

                    b.HasOne("PassengerManager.Shared.Models.Vehicle", "Vehicle")
                        .WithMany("Shifts")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("shifts_vehicle_id_fkey");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Telemetry", b =>
                {
                    b.HasOne("PassengerManager.Shared.Models.User", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .HasConstraintName("telemetry_driver_id_fkey");

                    b.HasOne("PassengerManager.Shared.Models.Route", "Route")
                        .WithMany("Telemetries")
                        .HasForeignKey("RouteId")
                        .HasConstraintName("telemetry_route_id_fkey");

                    b.HasOne("PassengerManager.Shared.Models.Vehicle", "Vehicle")
                        .WithMany("Telemetries")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("telemetry_vehicle_id_fkey");

                    b.Navigation("Driver");

                    b.Navigation("Route");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Transaction", b =>
                {
                    b.HasOne("PassengerManager.Shared.Models.Route", "Route")
                        .WithMany("Transactions")
                        .HasForeignKey("RouteId")
                        .HasConstraintName("transactions_route_id_fkey");

                    b.HasOne("PassengerManager.Shared.Models.Vehicle", "Vehicle")
                        .WithMany("Transactions")
                        .HasForeignKey("VehicleId")
                        .HasConstraintName("transactions_vehicle_id_fkey");

                    b.Navigation("Route");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Trip", b =>
                {
                    b.HasOne("PassengerManager.Shared.Models.Route", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .HasConstraintName("trips_route_id_fkey");

                    b.HasOne("PassengerManager.Shared.Models.ShapeHeader", "Shape")
                        .WithMany("Trips")
                        .HasForeignKey("ShapeId")
                        .HasConstraintName("trips_shape_id_fkey");

                    b.Navigation("Route");

                    b.Navigation("Shape");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.TripUpdate", b =>
                {
                    b.HasOne("PassengerManager.Shared.Models.Trip", "Trip")
                        .WithMany("TripUpdates")
                        .HasForeignKey("TripId")
                        .HasConstraintName("trip_updates_trip_id_fkey");

                    b.HasOne("PassengerManager.Shared.Models.Vehicle", "Vehicle")
                        .WithMany("TripUpdates")
                        .HasForeignKey("VehicleId")
                        .HasConstraintName("trip_updates_vehicle_id_fkey");

                    b.Navigation("Trip");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.User", b =>
                {
                    b.HasOne("PassengerManager.Shared.Models.Agency", "Agency")
                        .WithMany("Users")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("users_agency_id_fkey");

                    b.HasOne("PassengerManager.Shared.Models.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("users_role_id_fkey");

                    b.Navigation("Agency");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Vehicle", b =>
                {
                    b.HasOne("PassengerManager.Shared.Models.Agency", "Agency")
                        .WithMany("Vehicles")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("vehicles_agency_id_fkey");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Agency", b =>
                {
                    b.Navigation("Routes");

                    b.Navigation("ServiceAlerts");

                    b.Navigation("Users");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Route", b =>
                {
                    b.Navigation("ServiceAlerts");

                    b.Navigation("Telemetries");

                    b.Navigation("Transactions");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.ShapeHeader", b =>
                {
                    b.Navigation("ShapePoints");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Stop", b =>
                {
                    b.Navigation("ServiceAlerts");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Trip", b =>
                {
                    b.Navigation("TripUpdates");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.User", b =>
                {
                    b.Navigation("LoginAudits");

                    b.Navigation("PasswordHistories");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PassengerManager.Shared.Models.Vehicle", b =>
                {
                    b.Navigation("Shifts");

                    b.Navigation("Telemetries");

                    b.Navigation("Transactions");

                    b.Navigation("TripUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
