syntax = "proto3";

import "google/api/annotations.proto";

option csharp_namespace = "PassengerManager.Shared.Protos";

package telemetry;

service CommunicationService
{
	rpc InitiateCall (InitiateCallRequest) returns (InitiateCallResponse)
	{
		option (google.api.http) =
		{
			post: "/v1/call"
			body: "*"
		};
	}

	rpc EndCall (EndCallRequest) returns (EndCallResponse)
	{
		option (google.api.http) =
		{
			post: "/v1/call/end"
			body: "*"
		};
	}
}

message InitiateCallRequest
{
	enum CallType
	{
		STANDARD = 0;
		EMERGENCY = 1;
	}

	CallType call_type = 1;
	string target_id = 2;
}

message InitiateCallResponse
{
	bool success = 1;
	string message = 2;
	string assigned_target_id = 3;
	string call_id = 4;
}

message EndCallRequest
{
	string call_id = 1;
   InitiateCallRequest.CallType call_type = 2;
}

message EndCallResponse
{
	bool success = 1;
	string message = 2;
}


