syntax = "proto3";

option csharp_namespace = "PassengerManager.Shared.Protos";

package passenger_manager;

service TransportService 
{
    rpc Ping (Empty) returns (PingResponse);
    rpc LoginDriver (LoginRequest) returns (LoginResponse);
}

message Empty {}

message PingResponse 
{
    bool is_alive = 1;
    string server_time = 2;
} 

message LoginRequest 
{
    string username = 1;
    string password = 2;
    string vehicle_id = 3;
}

message LoginResponse 
{
    bool success = 1;
    string message = 2;
    string token = 3;
    string full_name = 4;
}